language: node_js
node_js:
  - "8"
dist: trusty # needs Ubuntu Trusty
script:
  - npm run release
os:
#- windows
- linux
- osx
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
    os: linux
