
name: CI Secure Tunnel

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Build and compile secure tunnel
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm ci
          npm run release
