
name: CI Secure Tunnel

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Test secure tunnel
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm ci
          npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2

      - name: Build and compile secure tunnel
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: |
          npm ci
          npm run release
      
      - name: Archive artifacts 
        uses: actions/upload-artifact@v2
        with:
          name: secure-tunnel-artifacts
          path: |
            bin/*
            doc/*
            README.md
            README.html
            path/output/test-results
            !path/**/*.tmp

      - name: Release secure tunnel
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
