name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and compile secure tunnel
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          npm ci
          npm run release

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: secure-tunnel-artifacts
          path: |
            bin/*
            doc/*
            README.md
            README.html
            path/output/test-results
            !path/**/*.tmp

      - name: Release secure tunnel
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
